### ISSUE TITLE
阅读感想+问题反馈

### ISSUE THREAD

**Issue by yemingshen** [Guyutongxue/MyCppTutorial#20]
> Written with [StackEdit](https://stackedit.io/).

# 阅读感想

作为一名大一学生，在上学期学完计概A后，寒假来看学长的[C++教程](https://learn-cpp.tk)，不仅巩固了上半学期所学，而且有拓展，有新的收获。首先，能够看出来学长很不容易，写出这本教程本身就要求作者对于相关知识烂熟于胸；其次，本书很有特色，从一位学习者的角度来阐述C++的基础框架，自然要比晦涩难懂的官方教程来的平易近人许多。

另外，希望学长多多努力，想要看到TBC（未完成）的内容呀！🥹

# 问题反馈

## 1. [第七章 继承与多态-多态-虚构函数](https://learn-cpp.tk/ch07/polymorphism/virtual_destructor.html)

> ### 形成抽象类
> 
> 此外，如果希望某<u>**各**</u>类成为抽象类，但没有其余合适的成为纯虚函数的成员时，可以选择将析构函数设置为纯虚的。

这里的 **某各类称为抽象类** 应改为 **某个类成为抽象类** 。

## 2. [第八章 模板基础-函数模板](https://learn-cpp.tk/ch08/function_template.html)

> ### 函数模板实参推导
> 
> 第三段话：函数模板实参推导通过一套<u>**及**</u>其复杂的流程实现。我们并不深究其原理，它在日常的使用中一般不会遇到麻烦。如果遇到了麻烦，我们也只需再次显式指定模板实参即可。

这里的 **及其复杂** 应改为 **极其复杂** 。

## 3. [第八章 模板基础-类模板](https://learn-cpp.tk/ch08/class_template.html)

第三段代码：
```cpp

template<typename T>
class C {
    T mem;

public:
    C(T mem) : mem{mem} { }
}；

int main() {
    C a(3); // 无需模板实参，推导出应生成 C<int> 类
}
```
这里 **public : C( T mem ) : mem { mem } { } ;** 的分号英文打成了中文。

## 4. [第八章 模板基础-默认实参](https://learn-cpp.tk/ch08/default_argument.html)

第一段代码
```cpp
template<int N = 42, int M = 56>
int add() {
    return N + M;
}
int main() {
    add<>()   // 实例化 add<42, 56>
    add<1>(); // 实例化 add<1, 56>
}
```
第一处注释处 **add<>()   // 实例化 add<42, 56>** 漏了分号。

## 5. [第十章 常用库介绍-移动语义与智能指针](https://learn-cpp.tk/ch10/smart_pointer/)

> ### 复制消除
> ```cpp
> struct S {
>    S() = default; // 不允许复制
>    S(const S&) = delete;
> };
> int main() {
>   S a(S{});
> }
> ```

这一段代码中的注释 **// 不允许复制** 应该下移一行。

## 6. [第十一章 函数式编程-STL算法-其他算法](https://learn-cpp.tk/ch11/stl_algorithms/others.html)

> -   在已排序范围上的算法：主要包括二分搜索和集合运算。严格上它们属于修改元素的算法，但它们自<u>**称**</u>体系，故单独列出。

这一段华中 **自称体系** 应改为 **自成体系** 。

## 7. [第十一章 函数式编程-语法进阶（选读）-预置比较](https://learn-cpp.tk/ch11/advanced/defaulted_compare.html)

段落末尾的代码：
```cpp
#include <compare> // 三路比较相关设施定义于此
#include <limits> // std::numeric_limits，见下

// 获取一个值为 NaN 的 double 类型常量
constexpr double NaN = std::numeric_limits<double>::quiet_NaN();

int main() {
    42 <=> 42; // std::strong_ordering::equivalent
    NaN <=> 1.0; // std::partial_ordering::unordered
}
```
和点击右上角显示出来的代码：
```cpp
#include  <compare>  // 三路比较相关设施定义于此

#include  <limits>  // std::numeric_limits，见下

// 获取一个值为 NaN 的 double 类型常量

constexpr  double NaN = std::numeric_limits<double>::quiet_NaN();

int  main()  {

42  <=>  42;  // std::strong_ordering::equivalent

NaN <=>  1.0;  // std::partial_ordering::unordered

// static_assert 是静态断言；如果括号内表达式为 false 导致编译错误

static_assert(42  <=>  42  == std::strong_ordering::equivalent);

static_assert(NaN <=>  1.0  == std::partial_ordering::unordered);

}
```
不一样，少了两行。

---

# 期待学长的新版本！🥰

**Comment by guyutongxue** [comment]
谢谢你的反馈！这些问题将在稍后的推送中修复（最后一个隐藏两行是有意而为的，似乎我当时不希望在正文中引入无关的语法。）

关于教程未来的打算，我现在还没有想好；主要是我离开北大之后就没有继续完善这份教程的目的了，所以最近一年都没有做大规模的更新，只有小的错误修复。目前的版本也有很多问题，比如很多地方（因为 C++ 本身的原因或者课程考点的需要）过于深入细节，也有很多地方讲得并不清楚或者脱离现实。我其实在考虑可能会完全重新写一份。
