### ISSUE TITLE
VS Code 环境配置工具网址过期

### ISSUE THREAD

**Issue by wanghaoyucn** [Guyutongxue/MyCppTutorial#22]
https://github.com/Guyutongxue/MyCppTutorial/blob/20a4685db81e4102dec8ec20c7ff149fa081cc9d/src/ch01/environment.md?plain=1#L34-L40

您好，VS Code配置工具的网址 `https://v4.vscch.tk/` 过期了，我百度了一下，发现您已经迁移到了 `https://vscch.guyutongxue.site/` ，后面的 Mac OS 和 Linux 部分也是如此，还望更新一下。

**Comment by guyutongxue** [comment]
thanks
