### ISSUE TITLE
捉个虫

### ISSUE THREAD

**Issue by ExilsZ** [Guyutongxue/MyCppTutorial#8]
ch05/overload，构造函数重载这里形参是`String(unsigned num, char c)`，
下文中的调用需要修改
`String a(5, "x");  // 调用重载 #1`
↓
`String a(5, 'x');  // 调用重载 #1`

**Comment by Guyutongxue** [comment]
谢谢！我会稍后更新。

您以后如果方便的话，可以直接在GitHub Issue中反馈，或者直接提Pull Request

发自我的iPhone

**Comment by guyutongxue** [comment]
Fixed in 7c1adab.

P.S. Sorry for wrong comment
